<a href="https://colab.research.google.com/github/Meaad96s/AVPDS/blob/master/Snippets_Importing_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra with Python


In [1]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt

In [10]:
A= np.array([[1,-2,3],[4,5,-6]])
print(A)

[[ 1 -2  3]
 [ 4  5 -6]]


In [9]:
B = np.array([[3,0,2],[-7,1,8]])
print(B)

[[ 3  0  2]
 [-7  1  8]]


In [12]:
A_plus_B = A+B
print("solution to A+B:\n",A+B)

solution to A+B:
 [[ 4 -2  5]
 [-3  6  2]]


In [15]:
AB_solution = 2*A-3*B
print(AB_solution)

[[ -7  -4   0]
 [ 29   7 -36]]


----------------------------------------------------------**2**

In [17]:
np.transpose(A+B) == np.transpose(A) + np.transpose(B)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])



```
`# 3 ##`
```



In [21]:
print("verify if (A+B).T=A.T+B.T:\n",np.allclose((A+B).T,A.T+B.T))

verify if (A+B).T=A.T+B.T:
 True


**Question 2**

---



---



In [23]:
A2 =  np.array([[1,3],[2,-1]])
A2

array([[ 1,  3],
       [ 2, -1]])

In [25]:
B2= np.array([[2,0],[3,-2]])
B2

array([[ 2,  0],
       [ 3, -2]])

In [28]:
AB = A2 @ B2
AB

array([[11, -6],
       [ 1,  2]])

In [30]:
BA = B2 @ A2
BA

array([[ 2,  6],
       [-1, 11]])

In [31]:
print("verify if AB and BA are equal:\n",np.allclose((A2 & B2), B2 @ A2))

verify if AB and BA are equal:
 False
